name: Publish library

on:
  release:
    types: [created]

env:
  NODE: 18
  HUSKY: 0

jobs:
  ci_tests:
    uses: ./.github/workflows/ci_tests.yml

  ci_publish:
    needs: ci_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE }}
          registry-url: https://registry.npmjs.org/
          cache: npm

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Cache .angular and node_modules
        uses: actions/cache@v3
        id: cache-step
        with:
          key: cache-ubuntu-latest-node${{ env.NODE }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            cache-ubuntu-latest-node${{ env.NODE }}-
          path: |
            .angular/cache
            node_modules

      - name: Install dependencies
        if: steps.cache-step.outputs.cache-hit != 'true'
        run: npm clean-install --engine-strict

      - name: Build
        working-directory: projects/lib
        run: npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DSI_HUG_NPM_TOKEN }}
        run: npm publish ./dist --access public
